### ISSUE TITLE
Error which prevents extension activation

### ISSUE THREAD

**Issue by tecosaur** [yzhang-gh/vscode-dic-completion#15]
Hello, me again. I've noticed the following error.

```
Here is the error stack:  TypeError: Cannot read property 'push' of undefined
	at words.forEach.word (/home/tec/.vscode/extensions/yzhang.dictionary-completion-0.8.2/out/src/completion.js:80:40)
	at Array.forEach (<anonymous>)
	at loadOtherWordsAndRebuildIndex (/home/tec/.vscode/extensions/yzhang.dictionary-completion-0.8.2/out/src/completion.js:77:11)
	at Object.activate (/home/tec/.vscode/extensions/yzhang.dictionary-completion-0.8.2/out/src/completion.js:12:5)
	at activate (/home/tec/.vscode/extensions/yzhang.dictionary-completion-0.8.2/out/src/extension.js:5:16)
	at Function._callActivateOptional (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46813:69)
	at Function._callActivate (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46804:25)
	at define._doActivateExtension.Promise.all.then.values (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46772:48)
```

This correspands to
```js
indexedComplItems[firstLetter].push(item);
```

Thanks,

tecosaur.

**Comment by yzhang-gh** [comment]
Are you using some external dict files? I guess there are some words starting with non-Latin letters.

**Comment by tecosaur** [comment]
I am indeed; I'll check for non-latin letters.

**Comment by tecosaur** [comment]
It does. For example "isn't" and "éclair". I've change the "é" to "e", and removed all the words with `'` and everything works :)

**Comment by tecosaur** [comment]
Would be nice if there was support for more than just the latin letter though…

**Comment by yzhang-gh** [comment]
Should be resolved now 😉 (see the dev build)

**Comment by tecosaur** [comment]
I've got another issue :smiling_imp: 

```
Activating extension `yzhang.dictionary-completion` failed:  Cannot read property 'document' of undefined
extensionHostProcess.js:32981
Here is the error stack:  TypeError: Cannot read property 'document' of undefined
	at loadOtherWordsAndRebuildIndex (/home/tec/.vscode/extensions/yzhang.dictionary-completion-0.8.2/out/src/completion.js:64:54)
	at Object.activate (/home/tec/.vscode/extensions/yzhang.dictionary-completion-0.8.2/out/src/completion.js:12:5)
	at activate (/home/tec/.vscode/extensions/yzhang.dictionary-completion-0.8.2/out/src/extension.js:5:16)
	at Function._callActivateOptional (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46813:69)
	at Function._callActivate (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46804:25)
	at define._doActivateExtension.Promise.all.then.values (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46772:48)
```

It seems that activation relies on `loadOtherWordsAndRebuildIndex` which contains `const activeDoc = vscode.window.activeTextEditor.document;`. Guess it isn't too happy when `vscode.window.activeTextEditor` is `undefined`.

Would be nice if it could activate when you have no files yet open, or are focused on one of those non-textEditor panes (like markdown preview).

**Comment by yzhang-gh** [comment]
Good catch 😂. Fixed again.
